package com.mycompany.pro1_paradigmas;


import com.mycompany.pro1_paradigmas.controller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Josue
 */
public class screen extends javax.swing.JFrame {

    /**
     * Creates new form screen
     */
    public screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        in_ta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        out_ta = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        file_btn = new javax.swing.JButton();
        play_btn = new javax.swing.JButton();
        stop_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        in_ta.setColumns(20);
        in_ta.setRows(5);
        jScrollPane1.setViewportView(in_ta);

        out_ta.setColumns(20);
        out_ta.setRows(5);
        jScrollPane2.setViewportView(out_ta);

        jToolBar1.setRollover(true);

        file_btn.setText("File");
        file_btn.setFocusable(false);
        file_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        file_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        file_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_btnActionPerformed(evt);
            }
        });
        jToolBar1.add(file_btn);

        play_btn.setText("Play");
        play_btn.setFocusable(false);
        play_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        play_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        play_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                play_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                play_btnMousePressed(evt);
            }
        });
        jToolBar1.add(play_btn);

        stop_btn.setText("Stop");
        stop_btn.setFocusable(false);
        stop_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stop_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(stop_btn);

        clear_btn.setText("Clear");
        clear_btn.setFocusable(false);
        clear_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clear_btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(clear_btn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_btnActionPerformed

    private void play_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_play_btnMouseClicked
        String a = in_ta.getText();
        
        out_ta.setText(a);
    }//GEN-LAST:event_play_btnMouseClicked

    private void play_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_play_btnMousePressed

        String a = in_ta.getText();
        
        controller.algo(a);
        
        out_ta.setText(a);
    }//GEN-LAST:event_play_btnMousePressed


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton file_btn;
    private javax.swing.JTextArea in_ta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea out_ta;
    private javax.swing.JButton play_btn;
    private javax.swing.JButton stop_btn;
    // End of variables declaration//GEN-END:variables
}
